# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Plugin-Redirect
version:      0.02
version_from: lib/Catalyst/Plugin/Redirect.pm
installdirs:  site
requires:
    Catalyst:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
